language: scala
git:
  depth: 100
cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup locks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
matrix:
  include:
    - os: linux
      jdk: openjdk11
      scala: 2.13.3
    - os: linux
      jdk: openjdk8
      scala: 2.12.12
    - os: linux
      jdk: openjdk8
      scala: 2.11.12
script:
  - sbt -batch ++$TRAVIS_SCALA_VERSION clean coverage test mimaReportBinaryIssues coverageAggregate coveralls
