language: scala
git:
  depth: 100
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier
before_cache:
  # Cleanup locks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
matrix:
  include:
    - os: linux
      jdk: openjdk11
      scala: 2.13.1
    - os: linux
      jdk: openjdk8
      scala: 2.12.10
    - os: linux
      jdk: openjdk8
      scala: 2.11.12
script:
  - sbt -no-colors ++$TRAVIS_SCALA_VERSION -Dsbt.supershell=false clean coverage test coverageAggregate mimaReportBinaryIssues
after_success:
  - bash <(curl -s https://codecov.io/bash)
